apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: golang-eks
  region: ap-south-1
availabilityZones:
  - ap-south-1a
  - ap-south-1b
managedNodeGroups:
  - name: general
    privateNetworking: true
    instanceType: t2.small
    desiredCapacity: 1

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 7