apiVersion: v1
kind: Service
metadata:
  name: golang-eks-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-address-type: ipv4
spec:
  selector:
    app: golang-eks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
